// datosPlatos.js

const platos = {
    pizza: [
        {nombre: 'Cuatro Sabores', img:'../img/img-main/pizza4sabores.png', descripcion: 'Escoge los sabores que mas te gusten!', precioMediana: 'Mediana $30.000', precioGrande: 'Grande $45.000'}
    ],
    pizzas: [
        // Vegetarianas
        {nombre: 'Caprino', img:'../img/img-menu/pizza.jpg', descripcion: 'Tomates secos, tomates frescos y champiñones', precioPersonal: 'Personal $11.500', precioMediana: 'Mediana $22.000', precioGrande: 'Grande $31.000'},
        {nombre: 'Napolitana', img:'../img/img-menu/pizza.jpg', descripcion: 'Rodajas de tomate y oregano', precioPersonal: 'Personal $10.500', precioMediana: 'Mediana $18.500', precioGrande: 'Grande $31.000'},
        {nombre: 'Primavera', img:'../img/img-menu/pizza.jpg', descripcion: 'Tomate en cuadros y albahaca', precioPersonal: 'Personal $10.500', precioMediana: 'Mediana $18.000', precioGrande: 'Grande $31.000'},
        {nombre: 'Vegetariana 100%', img:'../img/img-menu/pizza.jpg', descripcion: 'Aceitunas verdes, pimenton, cebolla, champiñones', precioPersonal: 'Personal $12.500', precioMediana: 'Mediana $21.500', precioGrande: 'Grande $31.000'},
        {nombre: 'Huerto Vegetales', img:'../img/img-menu/pizza.jpg', descripcion: 'Aceitunas verdes, champiñones, rúgula y salasa cesar', precioPersonal: 'Personal $14.000', precioMediana: 'Mediana $24.000', precioGrande: 'Grande $36.000'},
        {nombre: 'Traviata', img:'../img/img-menu/pizza.jpg', descripcion: 'Tomates secos, albahacac y queso parmesano', precioPersonal: 'Personal $14.000', precioMediana: 'Mediana $24.000', precioGrande: 'Grande $33.500'},
        // Pollo
        {nombre: 'Fox de huerto', img:'../img/img-menu/pizza.jpg', descripcion: 'Pollo, jamón, champiñones, rúgula y salsa cesar', precioPersonal: 'Personal $16.000', precioMediana: 'Mediana $28.000', precioGrande: 'Grande $40.000'},
        {nombre: 'Filipina', img:'../img/img-menu/pizza.jpg', descripcion: 'Pollo, tocineta, maíz tierno, aceitunas verdes, cebolla roja y rúgula', precioPersonal: 'Personal $13.000', precioMediana: 'Mediana $25.000', precioGrande: 'Grande $37.000'},
        {nombre: 'Mostaneza', img:'../img/img-menu/pizza.jpg', descripcion: 'Pollo bañado en salsa mostaneza y tomate en cuadros', precioPersonal: 'Personal $12.500', precioMediana: 'Mediana $23.000', precioGrande: 'Grande $36.000'},
        {nombre: 'Pollo BBQ', img:'../img/img-menu/pizza.jpg', descripcion: 'Pollo horneado bañado en salsa BBQ', precioPersonal: 'Personal $13.000', precioMediana: 'Mediana $24.000', precioGrande: 'Grande $38.000'},
        {nombre: 'Cuatro partes Fox', img:'../img/img-menu/pizza.jpg', descripcion: 'Pollo, jamón, champiñones y tomate en cuadros', precioPersonal: 'Personal $13.000', precioMediana: 'Mediana $23.000', precioGrande: 'Grande $36.000'},
        {nombre: 'Florida', img:'../img/img-menu/pizza.jpg', descripcion: 'Pollo horneado bañado en salsa napolitana, cebolla chip y maíz tierno', precioPersonal: 'Personal $12.000', precioMediana: 'Mediana $24.000', precioGrande: 'Grande $36.500'},
        {nombre: 'Pollo bechamel', img:'../img/img-menu/pizza.jpg', descripcion: 'Pollo horneado bañado en salsa bechamel y champiñones', precioPersonal: 'Personal $13.500', precioMediana: 'Mediana $24.000', precioGrande: 'Grande $34.500'},
        {nombre: 'Pollo carbonara', img:'../img/img-menu/pizza.jpg', descripcion: 'Pollo horneado, bañado en salsa bechamel y tocineta', precioPersonal: 'Personal $14.000', precioMediana: 'Mediana $26.000', precioGrande: 'Grande $38.500'},
        {nombre: 'Pollo champiñones', img:'../img/img-menu/pizza.jpg', descripcion: 'Pollo horneado y champiñones', precioPersonal: 'Personal $12.500', precioMediana: 'Mediana $24.000', precioGrande: 'Grande $35.000'},
        {nombre: 'Pollo miel mostaza', img:'../img/img-menu/pizza.jpg', descripcion: 'Pollo hornado bañado en salsa miel mostazay tocineta', precioPersonal: 'Personal $14.000', precioMediana: 'Mediana $25.000', precioGrande: 'Grande $37.500'},
        // Carne
        {nombre: 'Americana premiun(Picantica)', img:'../img/img-menu/pizza.jpg', descripcion: 'Pepperoni y jamón', precioPersonal: 'Personal $15.000', precioMediana: 'Mediana $27.500', precioGrande: 'Grande $40.000'},
        {nombre: 'Bey pepperoni (Picantica)', img:'../img/img-menu/pizza.jpg', descripcion: 'Pepperoni y tocineta', precioPersonal: 'Personal $15.000', precioMediana: 'Mediana $27.500', precioGrande: 'Grande $37.500'},
        {nombre: 'Bolognesa', img:'../img/img-menu/pizza.jpg', descripcion: 'Carne a la bolognesa, jamón y champiñones', precioPersonal: 'Personal $12.000', precioMediana: 'Mediana $23.000', precioGrande: 'Grande $34.000'},
        {nombre: 'California', img:'../img/img-menu/pizza.jpg', descripcion: 'Chorizo especial, carne molida, pimentón y cebolla morada', precioPersonal: 'Personal $13.000', precioMediana: 'Mediana $25.000', precioGrande: 'Grande $37.000'},
        {nombre: 'Camarón cebolla y jamón', img:'../img/img-menu/pizza.jpg', descripcion: 'Camarón, cebolla y jamón', precioPersonal: 'Personal $18.000', precioMediana: 'Mediana $28.000', precioGrande: 'Grande $41.000'},
        {nombre: 'Camarón al BBQ', img:'../img/img-menu/pizza.jpg', descripcion: 'Camarón BBQ, tomate en cuadros y piña', precioPersonal: 'Personal $18.000', precioMediana: 'Mediana $29.000', precioGrande: 'Grande $41.000'},
        {nombre: 'Camarón marinero', img:'../img/img-menu/pizza.jpg', descripcion: 'Camarones salteados en salsa marinera y cebolla', precioPersonal: 'Personal $18.000', precioMediana: 'Mediana $29.000', precioGrande: 'Grande $41.000'},
        {nombre: 'Costillas BBQ', img:'../img/img-menu/pizza.jpg', descripcion: 'trozos de costilla horeado en salsa BBQ', precioPersonal: 'Personal $13.500', precioMediana: 'Mediana $25.500', precioGrande: 'Grande $38.500'},
        {nombre: 'Criolla', img:'../img/img-menu/pizza.jpg', descripcion: 'Carne desmechada, chorizo especial y maíz tierno', precioPersonal: 'Personal $13.000', precioMediana: 'Mediana $25.500', precioGrande: 'Grande $38.500'},
        {nombre: 'Del campo', img:'../img/img-menu/pizza.jpg', descripcion: 'Carne molida, tocineta y maíz tierno', precioPersonal: 'Personal $13.000', precioMediana: 'Mediana $25.500', precioGrande: 'Grande $38.500'},
        {nombre: 'Genoveva', img:'../img/img-menu/pizza.jpg', descripcion: 'Chorizo español, champiñones, cebolla y pimentón', precioPersonal: 'Personal $11.500', precioMediana: 'Mediana $23.000', precioGrande: 'Grande $36.000'},
        {nombre: 'Jamón y queso', img:'../img/img-menu/pizza.jpg', descripcion: 'Jamón y queso', precioPersonal: 'Personal $11.500', precioMediana: 'Mediana $20.500', precioGrande: 'Grande $30.500'},
        {nombre: 'Lomito pimienta (Picantica)', img:'../img/img-menu/pizza.jpg', descripcion: 'Tirillas de lomo fino salteados en salsa pimienta', precioPersonal: 'Personal $14.500', precioMediana: 'Mediana $27.000', precioGrande: 'Grande $38.000'},
        {nombre: 'Madrileña', img:'../img/img-menu/pizza.jpg', descripcion: 'Jamóm serrano, pepperoni y chorizo español', precioPersonal: 'Personal $15.500', precioMediana: 'Mediana $29.000', precioGrande: 'Grande $41.000'},
        {nombre: 'Oriental', img:'../img/img-menu/pizza.jpg', descripcion: 'Lomo de res, pollo, champiñones y rices chinas, bañado en salsa oriental', precioPersonal: 'Personal $14.500', precioMediana: 'Mediana $26.500', precioGrande: 'Grande $39.500'},
        {nombre: 'Pepperoni maíz', img:'../img/img-menu/pizza.jpg', descripcion: 'Pepperoni y maíz tierno', precioPersonal: 'Personal $14.500', precioMediana: 'Mediana $27.000', precioGrande: 'Grande $39.000'},
        {nombre: 'Pepernata', img:'../img/img-menu/pizza.jpg', descripcion: 'Pepperoni, pimentón y cebolla morada', precioPersonal: 'Personal $13.000', precioMediana: 'Mediana $25.000', precioGrande: 'Grande $38.000'},
        {nombre: 'Pepperoni', img:'../img/img-menu/pizza.jpg', descripcion: 'Pepperoni y queso de la casa', precioPersonal: 'Personal $13.500', precioMediana: 'Mediana $25.000', precioGrande: 'Grande $38.500'},
        {nombre: 'Stroganoft', img:'../img/img-menu/pizza.jpg', descripcion: 'Tirillas de lomo fino, champiñones y rúgula', precioPersonal: 'Personal $13.000', precioMediana: 'Mediana $26.500', precioGrande: 'Grande $39.000'},
        {nombre: 'Tocineta maíz', img:'../img/img-menu/pizza.jpg', descripcion: 'Tocineta y maíz tierno', precioPersonal: 'Personal $13.500', precioMediana: 'Mediana $25.000', precioGrande: 'Grande $38.500'},
        {nombre: 'Renchera', img:'../img/img-menu/pizza.jpg', descripcion: 'Chorizo, tocineta y maíz tierno', precioPersonal: 'Personal $13.500', precioMediana: 'Mediana $25.000', precioGrande: 'Grande $39.500'},
        {nombre: 'Tocineta y jamón', img:'../img/img-menu/pizza.jpg', descripcion: 'jamón de cerdo ahmado y tocineta', precioPersonal: 'Personal $13.500', precioMediana: 'Mediana $24.000', precioGrande: 'Grande $39.500'},
        // Mexicanas
        {nombre: 'Chile (Picantica)', img:'../img/img-menu/pizza.jpg', descripcion: 'Carne a la bologesa, caraota y picante', precioPersonal: 'Personal $', precioMediana: 'Mediana $', precioGrande: 'Grande $'},
        {nombre: 'Jalisco (Picantica)', img:'../img/img-menu/pizza.jpg', descripcion: 'Carne a la bolognesa, chorizo especial y caraota', precioPersonal: 'Personal $12.000', precioMediana: 'Mediana $24.500', precioGrande: 'Grande $33.500'},
        {nombre: 'Picaleña(Picante)', img:'../img/img-menu/pizza.jpg', descripcion: 'Pepperoni, jalapeños, pimentón y cebolla morada', precioPersonal: 'Personal $13.000', precioMediana: 'Mediana $25.500', precioGrande: 'Grande $36.500'},
        {nombre: 'Texas Fox (Picantica)', img:'../img/img-menu/pizza.jpg', descripcion: 'Chriozo, caraota, pico de gallo y guacamole', precioPersonal: 'Personal $12.500', precioMediana: 'Mediana $25.500', precioGrande: 'Grande $33.000'},
        {nombre: 'Acapulco (Picantica)', img:'../img/img-menu/pizza.jpg', descripcion: 'Carne desmechada, cebolla morada, tomate en cuadros y tostacos', precioPersonal: 'Personal $13.500', precioMediana: 'Mediana $25.500', precioGrande: 'Grande $37.500'},
        // dulces
        {nombre: 'Hawaiana', img:'../img/img-menu/pizza.jpg', descripcion: 'Troxos de piña y jamón', precioPersonal: 'Personal $12.000', precioMediana: 'Mediana $20.500', precioGrande: 'Grande $32.000'},
        {nombre: 'Caribeña', img:'../img/img-menu/pizza.jpg', descripcion: 'Piña, durazno, pollo desmechado y cebolla caramelizada', precioPersonal: 'Personal $13.000', precioMediana: 'Mediana $25.000', precioGrande: 'Grande $34.000'},
        {nombre: 'Nutella', img:'../img/img-menu/pizza.jpg', descripcion: 'Fresas, banano y nutella', precioPersonal: 'Personal $13.500', precioMediana: 'Mediana $24.000', precioGrande: 'Grande $30.500'},
        {nombre: 'Paraiso', img:'../img/img-menu/pizza.jpg', descripcion: 'Jamón, durazno y ciruela', precioPersonal: 'Personal $13.000', precioMediana: 'Mediana $25.000', precioGrande: 'Grande $38.000'},
        {nombre: 'Tocineta y ciruela', img:'../img/img-menu/pizza.jpg', descripcion: 'Trozos de tocineta y ciruela', precioPersonal: 'Personal $13.000', precioMediana: 'Mediana $24.000', precioGrande: 'Grande $34.000'},
        {nombre: 'Tropical Fox', img:'../img/img-menu/pizza.jpg', descripcion: 'Piña, ciruela, cereza y durazno', precioPersonal: 'Personal $13.000', precioMediana: 'Mediana $24.000', precioGrande: 'Grande $37.000'},
        {nombre: 'Chorizo dulce', img:'../img/img-menu/pizza.jpg', descripcion: 'Chorizo dulce, Champiñones, pepperoni, cebolla y pimentón', precioPersonal: 'Personal $13.000', precioMediana: 'Mediana $25.000', precioGrande: 'Grande $38.500'},
        {nombre: 'Queso y bocadillo', img:'../img/img-menu/pizza.jpg', descripcion: 'Trozos de bocadillo beleño y queso', precioPersonal: 'Personal $12.000', precioMediana: 'Mediana $20.500', precioGrande: 'Grande $30.500'},
    ],
    lasagnas: [
        {nombre: 'Bolognesa', img:'../img/img-menu/lasagna.jpg', descripcion: 'Salsa a la bolognesa', precioPequeña: 'Pequeña $14.500', precioGrande: 'Grande $18.900'},
        {nombre: 'Camarón marinero', img:'../img/img-menu/lasagna.jpg', descripcion: 'Camarón, cebolla y salsa marinera', precioPequeña: 'Pequeña $17.000', precioGrande: 'Grande $21.400'},
        {nombre: 'Camarón BBQ', img:'../img/img-menu/lasagna.jpg', descripcion: 'Camarones al BBQ, tomota y piña', precioPequeña: 'Pequeña $17.000', precioGrande: 'Grande $21.500'},
        {nombre: 'Fox especial', img:'../img/img-menu/lasagna.jpg', descripcion: 'Pollo, jamón, champiñones y carne a la bolognesa', precioPequeña: 'Pequeña $16.500', precioGrande: 'Grande $21.000'},
        {nombre: 'Pollo con champiñones', img:'../img/img-menu/lasagna.jpg', descripcion: 'Pollo, champiñones y salsa bechamel', precioPequeña: 'Pequeña $15.000', precioGrande: 'Grande $18.900'},
        {nombre: 'Polo carbonara', img:'../img/img-menu/lasagna.jpg', descripcion: 'Pollo, tocineta y salsa bechamel', precioPequeña: 'Pequeña $15.500', precioGrande: 'Grande $19.900'},
        {nombre: 'Vegetariana', img:'../img/img-menu/lasagna.jpg', descripcion: 'Cebolla, pimentón, champiñones y salsa bechamel', precioPequeña: 'Pequeña $12.500', precioGrande: 'Grande $17.900'},
    ],
    spaguetis: [

        {nombre: 'Bolognsa', img: '../img/img-menu/pasta.jpg', descripcion: 'Carne a la bolognesa', precio:'$15.400'},
        {nombre: 'Camarones marinerps y ajo', img: '../img/img-menu/pasta.jpg', descripcion: 'Camarones en salsa marinera y cebolla', precio:'$20.900'},
        {nombre: 'Pollo carbonara', img: '../img/img-menu/pasta.jpg', descripcion: 'pollo, tocineta y salsa bechamel', precio:'$18.900'},
        {nombre: 'Pollo bechamel', img: '../img/img-menu/pasta.jpg', descripcion: 'pollo, champiñones y salsa bechamel', precio:'$15.400'},
        {nombre: 'Vegetariano', img: '../img/img-menu/pasta.jpg', descripcion: 'Cebolla morada, pimentón, champiñones, tomate, salsa bechamel y salsa napolitana', precio:'$14.900'},
    ],
    otros: [
        {nombre: 'Papas a la francesa', img: '../img/img-menu/francesa.jpg', descripcion: 'Papas fritas 250g', precio:'$5.500'},
        {nombre: 'Alitas BBQ', img: '../img/img-menu/francesa.jpg', descripcion: 'cuatro alas bañadas en salsa BBQ, acompañadas de papas a la francesa, patacón y ensalada', precio:'$15.500'},
        {nombre: 'Salchipapa sencilla', img: '../img/img-menu/francesa.jpg', descripcion: 'Papas a la francesa, salchicha americana y salsas', precio:'$9.500'},
        {nombre: 'Salchipapa con pollo', img: '../img/img-menu/francesa.jpg', descripcion: 'Papas a la francesa, salchicha americana, pollo desmechado, queso gratinado y salsas', precio:'$11.500'},
        {nombre: 'Salchipapa con carne', img: '../img/img-menu/francesa.jpg', descripcion: 'Papas a la francesa, salchicha americana, carne desmechada, queso gratinado y salsas', precio:'$12.500'},
        {nombre: 'Salchipapa especial', img: '../img/img-menu/francesa.jpg', descripcion: 'Papas a la francesa, salchicha americana, pollo y carne desmechada, queso gratinado y salsas', precio:'$14.000'},
        {nombre: 'Costillas BBQ', img: '../img/img-menu/francesa.jpg', descripcion: 'Costillas de cerdo bañadas en salsa BBQ, acompañadas de papas a la francesa, patacón y ensalada', precio:'$15.000'},
        {nombre: 'Perro caliente sencillo', img: '../img/img-menu/francesa.jpg', descripcion: 'Salchicha americana, cebolla, queso, huevo de codorniz, papa chip y salsas', precio:'$8.000'},
        {nombre: 'Perro caliente en combo', img: '../img/img-menu/francesa.jpg', descripcion: 'Salchicha americana, cebolla, queso, huevo de codorniz, papa chip y salsas con papas a la francesa y gaseosa', precio:'$14.000'},
        {nombre: 'Mazorcada ranchera', img: '../img/img-menu/francesa.jpg', descripcion: 'Maíz tierno, chirzo, tocineta, carne desmechada, papa chip, salsa napolitana y queso gratinado', precio:'$17.000'},
        {nombre: 'Mazorcada pollo champiñones', img: '../img/img-menu/francesa.jpg', descripcion: 'Maíz tierno, pollo desmechado, champiñones, papa chip, salsa bechamel y queso gratinado', precio:'$16.900'},
        {nombre: 'Mazorcada vegetariana', img: '../img/img-menu/francesa.jpg', descripcion: 'Maíz tierno, zuquini, champiñones, papa chip, salsa bechamel y queso gratinado', precio:'$14.900'},
    ],
    mexicano: [
        {nombre: 'Quesadillas', img: '../img/img-menu/quesadilla.jpg', descripcion: 'Tortillas de trigo, rellena de carne y/o pollo y queso, acompañado de guacamole y pico de gallo', precio:'$16.000'},
        {nombre: 'Burrito', img: '../img/img-menu/quesadilla.jpg', descripcion: 'Tortillas de trigo, rellena de carne y/o pollo, maíz tierno, queso y lechuga, acompañado de guacamole y tostacos', precio:'$18.000'},
        {nombre: 'Burrito vegetariano', img: '../img/img-menu/quesadilla.jpg', descripcion: 'Tortillas de trigo, rellena de zuquini, champiñones, maíz tierno, queso y lechuga, acompañado de guacamole y tostacos', precio:'$16.000'},
    ],
    hamburguesas: [
        {nombre: 'Sencilla', img: '../img/img-menu/hamburguesa.jpg', descripcion: 'Carne, lechuga, tomate, cebolla y queso', precio:'$9.000'},
        {nombre: 'Fox ranchera', img: '../img/img-menu/hamburguesa.jpg', descripcion: 'Carne, tocineta, maíz tierno, lechuga, tomate, cebolla y queso, acompañada de papas a la francesa', precio:'$16.900'},
        {nombre: 'Fox champiñón', img: '../img/img-menu/hamburguesa.jpg', descripcion: 'Carne, champiñones, lechuga, tomate, cebolla y queso, acompañada de papas a la francesa', precio:'$16.000'},
        {nombre: 'Fox miel mostaza', img: '../img/img-menu/hamburguesa.jpg', descripcion: 'Carne, pollo en salsa miel mostaza, lechuga, tomate, cebolla y queso, acompañada de papas a la francesa', precio:'$17.000'},
        {nombre: 'Fox del huerto', img: '../img/img-menu/hamburguesa.jpg', descripcion: 'Carne, pollo, jaón, champiñones, salsa cesar, lechuga, tomate, cebolla y queso, acompañada de papas a la francesa', precio:'$17.500'},
        {nombre: 'Combo sencilla', img: '../img/img-menu/hamburguesa.jpg', descripcion: 'Hamburguesa sencilla acompañada de papas a la francesa y gaseosa 250ml', precio:'$14.000'},
        {nombre: 'Combo especial', img: '../img/img-menu/hamburguesa.jpg', descripcion: 'Hamburguesa sencilla con doble carne y doble queso, acompañada de papas a la francesa y gaseosa 250ml', precio:'$17.000'},
    ],
    bebidas: [
        //naturales
        {nombre: 'Jugos en agua (variedad)', img: '../img/img-menu/jugos.jpg', precio:'$4.500'},
        {nombre: 'Jugos en leche (variedad)', img: '../img/img-menu/jugos.jpg', precio:'$5.000'},
        {nombre: 'Limonada natural', img: '../img/img-menu/jugos.jpg', precio:'$4.000'},
        {nombre: 'Limonada cerezada', img: '../img/img-menu/jugos.jpg', precio:'$4.500'},
        {nombre: 'Limonada de hierbabuena', img: '../img/img-menu/jugos.jpg', precio:'$4.500'},
        {nombre: 'Limonada de coco', img: '../img/img-menu/jugos.jpg', precio:'$5.000'},
        // gaseosas y cervezas
        {nombre: 'Agua sin gas', img: '../img/img-menu/jugos.jpg', precio:'$2.500'},
        {nombre: 'Agua con gas', img: '../img/img-menu/jugos.jpg', precio:'$3.000'},
        {nombre: 'Club colombia (dorada - roja)', img: '../img/img-menu/jugos.jpg', precio:'$5.000'},
        {nombre: 'Poker', img: '../img/img-menu/jugos.jpg', precio:'$4.000'},
        {nombre: 'Coronita', img: '../img/img-menu/jugos.jpg', precio:'$5.000'},
        {nombre: 'Corona', img: '../img/img-menu/jugos.jpg', precio:'$6.000'},
        {nombre: 'Gaseosa 1.5 (Productos coca cola)', img: '../img/img-menu/jugos.jpg', precio:'$7.500'},
        {nombre: 'Gaseosa 1.5 (Productos postobón)', img: '../img/img-menu/jugos.jpg', precio:'$6.500'},
        {nombre: 'Gaseosa 400', img: '../img/img-menu/jugos.jpg', precio:'$3.500'},
        {nombre: 'Gaseosa 350', img: '../img/img-menu/jugos.jpg', precio:'$3.000'},
        {nombre: 'Gaseosa 250', img: '../img/img-menu/jugos.jpg', precio:'$2.000'},

    ]
    // Agrega más categorías y platos según sea necesario
  }
  